[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && npm run build"
]

[start]
cmd = "NODE_ENV=production node backend/dist/index.js"
